export const taskTypeLabelMap: Record<string, string> = {
  trend_import: "批量导入热点",
  trend_fetch: "抓取实时热点",
  trend_created: "录入热点",
  trend_updated: "更新热点",
  topic_created: "创建选题",
  topic_generation: "AI 生成选题",
  batch_generate_topics: "批量生成选题",
  batch_generate_topics_from_tracked_articles: "批量生成参考文章选题",
  batch_create_projects: "批量建项目",
  batch_continue_projects: "批量续链",
  topic_updated: "更新选题",
  wechat_mp_import: "导入公众号文章",
  tracked_article_created: "录入参考文章",
  enrich_tracked_articles_metadata: "批量补全参考文章字段",
  project_created: "创建项目",
  outline_generation: "生成大纲",
  generate_outline: "生成大纲",
  outline_restored: "恢复大纲版本",
  draft_generation: "生成初稿",
  generate_draft: "生成初稿",
  draft_diagnosed: "运行内容诊断",
  polish_draft: "原创增强精修",
  draft_polished: "原创增强精修",
  draft_polished_from_diagnosis: "按诊断目标精修",
  draft_restored: "恢复初稿版本",
  polish_and_generate_assets: "原创增强后生成素材包",
  assets_generation: "生成素材",
  generate_assets: "生成素材包",
  cover_image_regenerated: "重生成封面图",
  regenerate_cover_image: "重生成封面图",
  assets_restored: "恢复素材版本",
  publish_package_built: "导出发布包",
  polish_and_build_publish_package: "原创增强后生成发布包",
  build_publish_package: "生成发布包",
  approve_publish_package: "通过发布审核",
  publish_review: "发布审核",
  request_publish_revision: "请求发布修改",
  regenerate_from_review: "按审核意见重生成",
  project_retro_recorded: "记录项目复盘",
  creative_review_report_generated: "生成创作复盘",
  creative_pattern_promoted: "推广创作模式",
};

export function getTaskTypeLabel(taskType?: string): string {
  if (!taskType) {
    return "未知动作";
  }
  return taskTypeLabelMap[taskType] ?? taskType;
}
